// Build rca_data.js from the IGCC Daily RCA bucketing export.
// Sources (updated 2026-10-05):
//   IGCC bucketing/Bucketing/IGCC Daily RCA - Bucketing v2.csv   (one row per IGCC claim, 2026-08-18 → 09-22)
//   IGCC bucketing/Igcc reasons/IGCC Daily RCA - IGCC_REAONS.csv (reason → bucket map)
// Output rows: [date, storeId, itemName, bucket, reason, imgMatch] — one per claim.
// Store metadata (name/city/tier) is joined at runtime in dashboard.html.
const fs = require('fs');
const path = require('path');
const ROOT = __dirname;

const BUCKET_CSV = path.join(ROOT, 'IGCC bucketing', 'Bucketing', 'IGCC Daily RCA - Bucketing v2.csv');
const REASONS_CSV = path.join(ROOT, 'IGCC bucketing', 'Igcc reasons', 'IGCC Daily RCA - IGCC_REAONS.csv');
const OUT = path.join(ROOT, 'rca_data.js');

function parseCSVLine(line) {
  const out = []; let cur = '', inQ = false;
  for (let i = 0; i < line.length; i++) {
    const c = line[i];
    if (inQ) {
      if (c === '"') { if (line[i + 1] === '"') { cur += '"'; i++; } else inQ = false; }
      else cur += c;
    } else {
      if (c === '"') inQ = true;
      else if (c === ',') { out.push(cur); cur = ''; }
      else cur += c;
    }
  }
  out.push(cur);
  return out;
}

// ---------- reason → bucket map ----------
const reasonBucket = {};
{
  const lines = fs.readFileSync(REASONS_CSV, 'utf8').trim().split(/\r?\n/);
  const hdr = parseCSVLine(lines[0]);
  const iR = hdr.indexOf('IGCC_REASON'), iB = hdr.indexOf('Bucket');
  for (let i = 1; i < lines.length; i++) {
    if (!lines[i].trim()) continue;
    const p = parseCSVLine(lines[i]);
    reasonBucket[p[iR].trim()] = p[iB].trim();
  }
}

// ---------- claims ----------
const rows = [];
let skipped = 0, bucketMismatch = 0;
{
  const lines = fs.readFileSync(BUCKET_CSV, 'utf8').trim().split(/\r?\n/);
  const hdr = parseCSVLine(lines[0]);
  const iDT = hdr.indexOf('DT'), iStore = hdr.indexOf('STORE_ID'), iItem = hdr.indexOf('ITEM_NAME'),
        iBucket = hdr.indexOf('BUCKET'), iReason = hdr.indexOf('REASON'), iMatch = hdr.indexOf('IMG_MATCH');
  for (let i = 1; i < lines.length; i++) {
    if (!lines[i].trim()) continue;
    const p = parseCSVLine(lines[i]);
    const dt = p[iDT], store = parseInt(p[iStore], 10);
    if (!/^\d{4}-\d{2}-\d{2}$/.test(dt) || !Number.isFinite(store)) { skipped++; continue; }
    const reason = p[iReason].trim();
    let bucket = p[iBucket].trim();
    // cross-check against the reasons sheet; trust the sheet when they disagree
    const mapped = reasonBucket[reason];
    if (mapped && mapped !== bucket) { bucketMismatch++; bucket = mapped; }
    rows.push([dt, store, p[iItem], bucket, reason, p[iMatch].trim()]);
  }
}

const buckets = [...new Set(rows.map(r => r[3]))].sort();
const reasons = [...new Set(rows.map(r => r[4]))].sort();
const dates = [...new Set(rows.map(r => r[0]))].sort();
const stores = [...new Set(rows.map(r => r[1]))].sort((a, b) => a - b);

const js = `// Auto-generated by build_rca_data.js — do not edit by hand.
// One row per bucketed IGCC claim: [date, storeId, itemName, bucket, reason, imgMatch]
// Bucket legend: Pod = pod/store handling · CX = customer perception/false claim · Sourcing = upstream quality · WH = warehouse/packing
const RCA_ROWS = ${JSON.stringify(rows)};
const RCA_REASON_BUCKET = ${JSON.stringify(reasonBucket)};
`;
fs.writeFileSync(OUT, js);

console.log(`rca_data.js written: ${rows.length} claims (${skipped} skipped, ${bucketMismatch} bucket mismatches fixed)`);
console.log(`  dates ${dates[0]} → ${dates[dates.length - 1]} · ${stores.length} stores · ${buckets.length} buckets · ${reasons.length} reasons`);
console.log(`  size: ${(fs.statSync(OUT).size / 1e6).toFixed(2)} MB`);
